Python 3.10.0 (tags/v3.10.0:b494f59, Oct  4 2021, 19:00:18) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.

= RESTART: C:/Users/mmaya/OneDrive/Desktop/pythonlabsunnysir/execution time by file handling.py
Traceback (most recent call last):
  File "C:/Users/mmaya/OneDrive/Desktop/pythonlabsunnysir/execution time by file handling.py", line 2, in <module>
    f.open("mysecondfile","w")
NameError: name 'f' is not defined

= RESTART: C:/Users/mmaya/OneDrive/Desktop/pythonlabsunnysir/execution time by file handling.py
Traceback (most recent call last):
  File "C:/Users/mmaya/OneDrive/Desktop/pythonlabsunnysir/execution time by file handling.py", line 2, in <module>
    f.open("mysecondfile","w")
NameError: name 'f' is not defined

= RESTART: C:/Users/mmaya/OneDrive/Desktop/pythonlabsunnysir/execution time by file handling.py
Traceback (most recent call last):
  File "C:/Users/mmaya/OneDrive/Desktop/pythonlabsunnysir/execution time by file handling.py", line 2, in <module>
    f.open("mysecondfile.txt","w")
NameError: name 'f' is not defined

= RESTART: C:/Users/mmaya/OneDrive/Desktop/pythonlabsunnysir/execution time by file handling.py
Traceback (most recent call last):
  File "C:/Users/mmaya/OneDrive/Desktop/pythonlabsunnysir/execution time by file handling.py", line 3, in <module>
    start=time()
TypeError: 'module' object is not callable

= RESTART: C:/Users/mmaya/OneDrive/Desktop/pythonlabsunnysir/execution time by file handling.py
Traceback (most recent call last):
  File "C:/Users/mmaya/OneDrive/Desktop/pythonlabsunnysir/execution time by file handling.py", line 3, in <module>
    start=time()
TypeError: 'module' object is not callable

= RESTART: C:/Users/mmaya/OneDrive/Desktop/pythonlabsunnysir/execution time by file handling.py
enter the number4
24
time of execution iss 2.5696616172790527
enter the number4
24

= RESTART: C:/Users/mmaya/OneDrive/Desktop/pythonlabsunnysir/execution time by file handling.py
enter the number4
24
Traceback (most recent call last):
  File "C:/Users/mmaya/OneDrive/Desktop/pythonlabsunnysir/execution time by file handling.py", line 12, in <module>
    end=time()
TypeError: 'module' object is not callable

= RESTART: C:/Users/mmaya/OneDrive/Desktop/pythonlabsunnysir/execution time by file handling.py
enter the number4
factorial of 4 is 24
time of execution iss 2.411705732345581
Traceback (most recent call last):
  File "C:/Users/mmaya/OneDrive/Desktop/pythonlabsunnysir/execution time by file handling.py", line 23, in <module>
    s=time.time()
AttributeError: 'builtin_function_or_method' object has no attribute 'time'

= RESTART: C:/Users/mmaya/OneDrive/Desktop/pythonlabsunnysir/execution time by file handling.py
enter the number4
factorial of 4 is 24
time of execution iss 2.84519100189209
enter the number4
factorial of 4 is 24
time of execution by recursion methon of 4 is 4.836260080337524

= RESTART: C:/Users/mmaya/OneDrive/Desktop/pythonlabsunnysir/execution time by file handling.py
enter the number4
factorial of  4 by iteartion method is 24
time of execution is by iteration method is 4.852867603302002
enter the number4
factorial of 4  by recursion method  is 24
time of execution by recursion methon of 4 is 14.434782981872559

= RESTART: C:/Users/mmaya/OneDrive/Desktop/pythonlabsunnysir/execution time by file handling.py
enter the number4
factorial of  4 by iteartion method is 24
time of execution is by iteration method is 1.7883083820343018
enter the number4
factorial of 4  by recursion method  is 24
time of execution by recursion methon of 4 is 4.954807281494141
